export const exaltData = {
  solar: {
    abilities: {
      dawn: ["archery", "martial-arts", "melee", "thrown", "war"],
      zenith: [
        "integrity",
        "performance",
        "presence",
        "resistance",
        "survival",
      ],
      twilight: ["craft", "investigation", "lore", "medicine", "occult"],
      night: ["athletics", "awareness", "dodge", "larceny", "stealth"],
      eclipse: ["bureaucracy", "linguistics", "ride", "sail", "socialize"],
    },
    backgrounds: [
      "Allies",
      "Artifact",
      "Backing",
      "Contacts",
      "Cult",
      "Familiar",
      "Followers",
      "Influence",
      "Manse",
      "Mentor",
      "Resources",
    ],
    health: {
      zero: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      one: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  infernal: {
    abilities: {
      slayer: ["archery", "martial-arts", "melee", "thrown", "war"],
      malefactor: [
        "integrity",
        "performance",
        "presence",
        "resistance",
        "survival",
      ],
      defiler: ["craft", "investigation", "lore", "medicine", "occult"],
      scourge: ["athletics", "awareness", "dodge", "larceny", "stealth"],
      fiend: ["bureaucracy", "linguistics", "ride", "sail", "socialize"],
    },
    backgrounds: [
      "Allies",
      "Artifact",
      "Backing",
      "Contacts",
      "Cult",
      "Familiar",
      "Familiar (Demonic)",
      "Followers",
      "Influence",
      "Manse",
      "Mentor",
      "Past Life",
      "Resources",
      "Savant",
      "Spies",
    ],
    health: {
      zero: [[""]],
      one: [["", ""]],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      four: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  abyssal: {
    abilities: {
      dusk: ["archery", "martial-arts", "melee", "thrown", "war"],
      midnight: [
        "integrity",
        "performance",
        "presence",
        "resistance",
        "survival",
      ],
      daybreak: ["craft", "investigation", "lore", "medicine", "occult"],
      day: ["athletics", "awareness", "dodge", "larceny", "stealth"],
      moonshadow: ["bureaucracy", "linguistics", "ride", "sail", "socialize"],
    },
    backgrounds: [
      "Abyssal Command",
      "Allies",
      "Artifact",
      "Backing",
      "Contacts",
      "Cult",
      "Familiar",
      "Followers",
      "Influence",
      "Liege",
      "Manse",
      "Mentor",
      "Resources",
      "Spies",
      "Underworld Manse",
      "Whispers",
    ],
    health: {
      zero: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      one: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  lunar: {
    abilities: {
      war: [
        "archery",
        "athletics",
        "awareness",
        "dodge",
        "integrity",
        "martial-arts",
        "melee",
        "resistance",
        "thrown",
        "war",
      ],
      life: [
        "craft",
        "larceny",
        "linguistics",
        "performance",
        "presence",
        "ride",
        "sail",
        "socialize",
        "stealth",
        "survival",
      ],
      wisdom: [
        "bureaucracy",
        "investigation",
        "lore",
        "medicine",
        "occult",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    attributes: {
      casteless: [],
      "changing-moon": ["dexterity"],
      "full-moon": ["strength"],
      "no-moon": ["stamina"],
    },
    backgrounds: [
      "Allies",
      "Artifact",
      "Backing",
      "Contacts",
      "Cult",
      "Familiar",
      "Followers",
      "Heart's Blood",
      "Influence",
      "Manse",
      "Mentor",
      "Reputation",
      "Resources",
      "Solar Bond",
      "Taboo",
      "Tattoo Artifact",
    ],
    health: {
      zero: [[""]],
      one: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  sidereal: {
    abilities: {
      journeys: ["resistance", "ride", "sail", "survival", "thrown"],
      serenity: ["craft", "dodge", "linguistics", "performance", "socialize"],
      battles: ["archery", "athletics", "melee", "presence", "war"],
      secrets: ["investigation", "larceny", "lore", "occult", "stealth"],
      endings: [
        "awareness",
        "bureaucracy",
        "integrity",
        "martial-arts",
        "medicine",
      ],
    },
    backgrounds: [
      "Acquaintances",
      "Allies",
      "Artifact",
      "Backing",
      "Celestial Manse",
      "Connections",
      "Cult",
      "Familiar",
      "Followers",
      "Manse",
      "Mentor",
      "Resources",
      "Salary",
      "Savant",
      "Sifu",
    ],
    health: {
      zero: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      one: [[""]],
      two: [[""]],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  "dragon-blooded": {
    abilities: {
      air: ["linguistics", "lore", "occult", "stealth", "thrown"],
      earth: ["awareness", "craft", "integrity", "resistance", "war"],
      fire: ["athletics", "dodge", "melee", "presence", "socialize"],
      water: [
        "bureaucracy",
        "investigation",
        "larceny",
        "martial-arts",
        "sail",
      ],
      wood: ["archery", "medicine", "performance", "ride", "survival"],
    },
    backgrounds: [
      "Allies",
      "Arsenal",
      "Artifact",
      "Backing",
      "Breeding",
      "Command",
      "Connections",
      "Familiar",
      "Family",
      "Henchmen",
      "Manse",
      "Mentor",
      "Reputation",
      "Resources",
      "Retainers",
    ],
    health: {
      zero: [[""]],
      one: [
        ["", "", "locked", "locked", "locked", "locked"],
        ["locked", "locked", "locked", "locked", "locked", "locked"],
      ],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  "heroic-mortal": {
    abilities: {
      warrior: ["archery", "martial-arts", "melee", "thrown", "war"],
      priest: [
        "integrity",
        "performance",
        "presence",
        "resistance",
        "survival",
      ],
      savant: ["craft", "investigation", "lore", "medicine", "occult"],
      criminal: ["athletics", "awareness", "dodge", "larceny", "stealth"],
      broker: ["bureaucracy", "linguistics", "ride", "sail", "socialize"],
    },
    backgrounds: [
      "Allies",
      "Artifact",
      "Backing",
      "Command",
      "Contacts",
      "Destiny",
      "Esoteric Knowledge",
      "Face",
      "Familiar",
      "Followers",
      "Henchmen",
      "Influence",
      "Library",
      "Manse",
      "Mentor",
      "Patron",
      "Resources",
      "Retainers",
      "Sifu",
      "Spies",
    ],
    health: {
      zero: [["", "locked", "locked", "locked", "locked", "locked"]],
      one: [
        ["", "", "locked", "locked", "locked", "locked"],
        ["locked", "locked", "locked", "locked", "locked", "locked"],
      ],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        [
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
  alchemical: {
    abilities: {
      warfare: [
        "archery",
        "athletics",
        "awareness",
        "dodge",
        "integrity",
        "martial-arts",
        "melee",
        "resistance",
        "thrown",
        "war",
      ],
      labor: [
        "craft",
        "larceny",
        "linguistics",
        "performance",
        "presence",
        "ride",
        "sail",
        "socialize",
        "stealth",
        "survival",
      ],
      learning: ["bureaucracy", "investigation", "lore", "medicine", "occult"],
    },
    attributes: {
      orichalcum: ["strength", "charisma", "intelligence"],
      moonsilver: ["dexterity", "appearance", "wits"],
      starmetal: ["dexterity", "manipulation", "intelligence"],
      jade: ["stamina", "charisma", "wits"],
      soulsteel: ["stamina", "manipulation", "perception"],
      adamant: ["strength", "appearance", "perception"],
    },
    backgrounds: [
      "Allies",
      "Artifact",
      "Backing",
      "Charms",
      "Class",
      "Command",
      "Contacts",
      "Eidolon",
      "Familiar",
      "Savant",
    ],
    health: {
      zero: [[""]],
      one: [
        ["", "", "locked", "locked", "locked", "locked"],
        ["locked", "locked", "locked", "locked", "locked", "locked"],
      ],
      two: [
        [
          "",
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
        ["locked", "locked", "locked", "locked", "locked", "locked", "locked"],
      ],
      four: [[""]],
      incapacitated: [[""]],
      dying: [
        [
          "",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
          "locked",
        ],
      ],
    },
  },
};
