export const initialValues = {
  charms: [
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
    {
      name: "",
      cost: "",
      duration: "",
      type: "",
      keywords: "",
      effect: "",
      use: false,
    },
  ],
  combos: [
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
    { name: "", cost: "", charms: "" },
  ],
  sorcery: [
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
    { name: "", cost: "", duration: "", type: "", target: "", effect: "" },
  ],
  artifacts: [
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
    { name: "", rating: "", description: "" },
  ],
  manse: [
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
  ],
  backgrounds: [
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
    { name: "", rating: 0, description: "" },
  ],
  astrology: [
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
    {
      type: "",
      providence: "",
      scope: "",
      frequency: "",
      duration: "",
      trigger: "",
    },
  ],
  heartsBlood: [
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
    { name: "", look: "", effect: "" },
  ],
};
